[book]
authors = ["The Funkin' Crew Inc.", "EliteMasterEric", "Pi"]
language = "ja"
multilingual = false
src = "src"
title = "Friday Night Funkin' Modding ドキュメント 日本語版 (非公式)"


[output.html]
git-repository-url = "https://github.com/Pnap-c/funkin-modding-docs-japanese-translation/tree/main"
edit-url-template = "https://github.com/Pnap-c/funkin-modding-docs-japanese-translation/edit/main/{path}"
